-- ============================================================================
-- Seed canonical Bangalore localities from localities.py LOCALITY_META
-- ============================================================================

INSERT INTO localities (name, latitude, longitude, radius_km, aliases, also_include, zone, is_active)
VALUES
    ('Whitefield',       12.9698, 77.7499, 5.0, '{"whitefield","wtfd"}',                          '{"ITPL"}',    'East',    TRUE),
    ('HSR Layout',       12.9116, 77.6389, 3.0, '{"hsr layout","hsr"}',                           '{}',          'South',   TRUE),
    ('Koramangala',      12.9352, 77.6245, 3.0, '{"koramangala","koramangla"}',                    '{"Ejipura"}', 'South',   TRUE),
    ('Indiranagar',      12.9784, 77.6408, 2.5, '{"indiranagar","indira nagar"}',                  '{}',          'East',    TRUE),
    ('Marathahalli',     12.9591, 77.7010, 3.0, '{"marathahalli","marathalli","marthahalli"}',     '{}',          'East',    TRUE),
    ('Bellandur',        12.9257, 77.6761, 2.5, '{"bellandur","bellundur"}',                       '{}',          'East',    TRUE),
    ('BTM Layout',       12.9165, 77.6101, 2.5, '{"btm layout","btm"}',                           '{}',          'South',   TRUE),
    ('Hebbal',           13.0353, 77.5947, 3.0, '{"hebbal"}',                                     '{"Manyata"}', 'North',   TRUE),
    ('Yelahanka',        13.1007, 77.5963, 3.0, '{"yelahanka"}',                                  '{}',          'North',   TRUE),
    ('Electronic City',  12.8399, 77.6770, 4.0, '{"electronic city","ec","e-city","ecity"}',       '{}',          'South',   TRUE),
    ('Sarjapur Road',    12.9087, 77.6950, 3.5, '{"sarjapur road","sarjapur","sarjapura"}',        '{}',          'East',    TRUE),
    ('Hoodi',            12.9888, 77.7113, 2.0, '{"hoodi"}',                                      '{}',          'East',    TRUE),
    ('Jayanagar',        12.9299, 77.5820, 2.5, '{"jayanagar","jaya nagar"}',                     '{}',          'South',   TRUE),
    ('Bannerghatta',     12.8634, 77.5855, 3.0, '{"bannerghatta","bannerghatta road","bgr"}',     '{}',          'South',   TRUE),
    ('Cunningham Road',  12.9812, 77.5958, 2.0, '{"cunningham road","cunningham"}',                '{}',          'Central', FALSE),
    ('MG Road',          12.9756, 77.6099, 2.0, '{"mg road","mahatma gandhi road"}',               '{}',          'Central', FALSE),
    ('Frazer Town',      12.9854, 77.6146, 2.0, '{"frazer town","fraser town","frazier town"}',    '{}',          'Central', FALSE),
    ('Banaswadi',        13.0109, 77.6553, 2.5, '{"banaswadi","banasvadi"}',                       '{}',          'East',    TRUE),
    ('KR Puram',         13.0068, 77.6943, 2.5, '{"kr puram","krishnarajapuram"}',                 '{}',          'East',    TRUE),
    ('Domlur',           12.9609, 77.6387, 2.0, '{"domlur"}',                                     '{}',          'East',    FALSE),
    ('Madiwala',         12.9196, 77.6182, 2.0, '{"madiwala"}',                                   '{}',          'South',   FALSE),
    ('Bommanahalli',     12.8998, 77.6396, 2.5, '{"bommanahalli","bomanhalli"}',                   '{}',          'South',   TRUE),
    ('Brookefield',      12.9690, 77.7123, 2.0, '{"brookefield","brookfield","brook field"}',      '{}',          'East',    FALSE),
    ('Kadubeesanahalli', 12.9354, 77.7004, 2.0, '{"kadubeesanahalli","kadabeesanahalli","kdb halli"}', '{}',      'East',    FALSE),
    ('Panathur',         12.9344, 77.7127, 2.0, '{"panathur"}',                                   '{}',          'East',    FALSE),
    ('Varthur',          12.9352, 77.7489, 2.5, '{"varthur"}',                                    '{}',          'East',    FALSE),
    ('Thubarahalli',     12.9572, 77.7225, 2.0, '{"thubarahalli","tubrahalli"}',                   '{}',          'East',    FALSE),
    ('Kadugodi',         12.9775, 77.7593, 2.0, '{"kadugodi"}',                                   '{}',          'East',    FALSE),
    ('JP Nagar',         12.9077, 77.5851, 2.5, '{"jp nagar","j p nagar","jayaprakash nagar"}',   '{}',          'South',   TRUE),
    ('Banashankari',     12.9259, 77.5468, 2.5, '{"banashankari","bsk","banashankri"}',            '{}',          'West',    TRUE),
    ('Rajajinagar',      12.9899, 77.5530, 2.5, '{"rajajinagar","rajaji nagar"}',                  '{}',          'West',    TRUE),
    ('Malleshwaram',     13.0035, 77.5687, 2.5, '{"malleshwaram","malleswaram","malleshwarm"}',    '{}',          'West',    TRUE),
    ('Yeshwanthpur',     13.0265, 77.5449, 2.5, '{"yeshwanthpur","yeshwantpur","yeshvanthpur"}',   '{}',          'West',    TRUE),
    ('Nagawara',         13.0435, 77.6202, 2.5, '{"nagawara","nagavara"}',                         '{}',          'North',   FALSE),
    ('HBR Layout',       13.0277, 77.6384, 2.5, '{"hbr layout","hbr"}',                           '{}',          'North',   TRUE),
    ('CV Raman Nagar',   12.9848, 77.6618, 2.0, '{"cv raman nagar","cv raman"}',                   '{}',          'East',    FALSE),
    ('Old Airport Road', 12.9592, 77.6484, 2.0, '{"old airport road","oar"}',                      '{}',          'East',    FALSE),
    ('ITPL',             12.9854, 77.7308, 2.0, '{"itpl","international tech park"}',              '{}',          'East',    FALSE),
    ('Manyata',          13.0467, 77.6210, 2.0, '{"manyata","manyata tech park"}',                 '{}',          'North',   FALSE),
    ('Thanisandra',      13.0590, 77.6350, 2.0, '{"thanisandra","thanisandhra"}',                   '{}',          'North',   FALSE),
    ('Hennur',           13.0440, 77.6480, 2.5, '{"hennur","hennur road"}',                        '{}',          'North',   FALSE),
    ('Kalyan Nagar',     13.0254, 77.6400, 2.0, '{"kalyan nagar","kalyannagar"}',                  '{}',          'North',   FALSE),
    ('RT Nagar',         13.0210, 77.5970, 2.0, '{"rt nagar","r t nagar"}',                        '{}',          'North',   FALSE),
    ('Ejipura',          12.9420, 77.6220, 1.5, '{"ejipura"}',                                    '{}',          'South',   FALSE),
    ('Ulsoor',           12.9810, 77.6200, 1.5, '{"ulsoor","halasuru"}',                           '{}',          'Central', FALSE),
    ('Basavanagudi',     12.9420, 77.5730, 2.0, '{"basavanagudi","basavangudi"}',                  '{}',          'South',   FALSE),
    ('Sadashivanagar',   13.0060, 77.5810, 2.0, '{"sadashivanagar","sadashiva nagar"}',            '{}',          'Central', FALSE),
    ('Vijayanagar',      12.9710, 77.5330, 2.0, '{"vijayanagar","vijaya nagar"}',                  '{}',          'West',    FALSE),
    ('Kengeri',          12.9070, 77.4850, 3.0, '{"kengeri"}',                                    '{}',          'West',    FALSE)
ON CONFLICT (name) DO UPDATE SET
    latitude     = EXCLUDED.latitude,
    longitude    = EXCLUDED.longitude,
    radius_km    = EXCLUDED.radius_km,
    aliases      = EXCLUDED.aliases,
    also_include = EXCLUDED.also_include,
    zone         = EXCLUDED.zone,
    is_active    = EXCLUDED.is_active;
